dashboard_user/urls.py
from django.urls import path
from dashboard_user.views import *

app_name = 'dashboard_user'

urlpatterns = [
    path('', show_reports, name='show_reports'),
    path('Laporan/', get_all_reports, name = 'get_all_reports'),
    path('SedangDitangani/', get_onprogress_reports, name='get_onprogress_reports'),
    path('SudahDitangani/',get_processed_reports, name = 'get_processed_reports'),
    path('BelumDitangani/', get_unprocessed_reports, name = 'get_unprocessed_reports'),
    path('Ditolak/',get_rejected_reports, name='get_rejected_reports'),
    path('Draft/', add_draft, name = 'add_draft'),
    path('ShowDraft/', show_draft_json, name = 'show_draft_json')
]

login_things/urls.py
from django.contrib import admin
from django.urls import path
from login_things.views import *

app_name = 'login'

urlpatterns = [
    path('login/', login_user, name='login_user'),
    path('register/', register_user, name='register_user'),
    path('register_admin/', register_user_admin, name='register_admin'),
    path('dummy/', dummy, name='dummy'),
    path('logout/', logout_user, name='logout'),
    path('profile/<int:id>', show_profile, name='show_profile'),
    path('error_page/', error_page, name='error_page'),
    path('json/', get_json, name='get_json'),
    path('dashboard/', get_dashboard, name='get_dashboard'),
]

main_page/urls.py
from django.urls import path
from main_page.views import *

app_name = 'main_page'

urlpatterns = [
    path('', show_main_page, name='show_main_page'),
    path('news_1/', show_news_1, name='show_news_1'),
    path('news_2/', show_news_2, name='show_news_2'),
    path('news_3/', show_news_3, name='show_news_3'),
    path('isi_form/', create_review, name='create_review'),
    path('json_review/', get_json, name='get_json'),
    path('json_name/', get_json_name, name='get_json_name'),

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard_user/', include('dashboard_user.urls')),
    path('submission_form/', include('submission_form.urls'), name='submission_form'),
    path('dashboard_admin/', include('dashboard_admin.urls')),
    path('', include('login_things.urls'), name='login'),
    path('', include('main_page.urls')),
    path('auth/', include('authentication.urls')),

]

submission_form/urls.py
from django.urls import path
from submission_form.views import add_report_flutter, show_form, get_json, create_report

app_name = 'submission_form'
urlpatterns = [
    path('', show_form, name='submission_form'),
    path('json/', get_json, name='get_json'),
    path('create/', create_report, name='create_report'),
    path('add_report_flutter/', add_report_flutter, name='add_from_flutter')
]

submission_form/models.py
from django.db import models
from django.conf import settings


# Create your models here.

# Report: Judul, Isi Laporan, Tanggal, Lokasi, Instansi, Pihak yang terlibat, Status

INSTITUTION_LEVEL = (
    ('Nasional', 'Nasional'),
    ('Provinsi', 'Provinsi'),
    ('Kabupaten/Kota', 'Kabupaten/Kota'),
    ('Kecamatan', 'Kecamatan'),
    ('Desa/Kelurahan', 'Desa/Kelurahan'),
)
class Report(models.Model):
    user_submission = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        related_name='user_submission'
    )
    
    admin_submission = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        related_name='admin_submission'
    )

    title = models.CharField(max_length=100)
    content = models.TextField()
    institution = models.CharField(max_length=100)
    institution_level = models.CharField(max_length=100, choices=INSTITUTION_LEVEL)
    involved_party = models.CharField(max_length=100)
    date = models.DateTimeField()
    location = models.CharField(max_length=100)
    status = models.CharField(max_length=100)

    def __str__(self):
        return self.title
    
    # urutannya PENDING, DIPROSES, SELESAI
    def update_status_next(self):
        if self.status == 'PENDING':
            self.status = 'DIPROSES'
        elif self.status == 'DIPROSES':
            self.status = 'SELESAI'
        else:
            self.status = 'SELESAI'
    
    # urutannya PENDING, DIPROSES, SELESAI
    def update_status_back(self):
        if self.status == 'SELESAI':
            self.status = 'DIPROSES'
        elif self.status == 'DIPROSES':
            self.status = 'PENDING'
        else:
            self.status = 'PENDING'

    def update_status_reject(self):
        self.status = 'REJECTED'

submission_form/forms.py
from django.forms import ModelForm
from submission_form.models import Report

class ReportForm(ModelForm):
    class Meta:
        model = Report
        fields = [
            "title",
            "content",
            "institution",
            "institution_level",
            "involved_party",
            "date",
            "location",
            ]

submission_form/views.py
import json
from submission_form.forms import ReportForm
from submission_form.models import Report
from login_things.models import User
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core import serializers
import random
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login/')
def show_form(request):
    if request.user.admin and not request.user.staff:
        return redirect("login:error_page")
    if not request.user.is_authenticated:
        nama = "belum login"
    else:
        nama = request.user.nama
    context = {'nama':nama}
    return render(request, 'form.html', context)

@login_required(login_url='/login/')
def get_json(request):
    data = Report.objects.filter(user_submission=request.user) # filter by user
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


@login_required(login_url='/login/')
def create_report(request):
    if request.user.admin and not request.user.staff:
        return redirect("login:error_page")
    data_admin = User.objects.filter(admin=True).filter(staff=False)
    if len(data_admin) != 0:
        index = random.randint(0, len(data_admin)-1)
    elif len(data_admin) == 0:
        index = -1

    # Logic Assign Admin
    # admin_assign = None
    # if len(data_admin) != 0:
    #     admin_assign = data_admin[0]
    #     for admin in data_admin:
    #         if admin.counter < admin_assign.counter:
    #             admin_assign = admin

    # print(data_admin[0])
    if request.method == 'POST':
        # print(request.method)
        # create a form instance and populate it with data from the request:
        form = ReportForm(request.POST)
        
        if index == -1:
            dataAdmin = None
        else:
            dataAdmin = data_admin[index]
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            report = Report(
                user_submission = request.user,
                # admin_submission = admin_assign,
                admin_submission = dataAdmin,
                title = form.cleaned_data['title'],
                content = form.cleaned_data['content'],
                institution = form.cleaned_data['institution'],
                institution_level = form.cleaned_data['institution_level'],
                involved_party = form.cleaned_data['involved_party'],
                location = form.cleaned_data['location'],
                date = form.cleaned_data['date'],
                status = "PENDING"
            )
            # admin_assign.counter += 1
            report.save()
            # redirect to a new URL:
            print("success")
            return HttpResponse(
                serializers.serialize("json", [report]),
                content_type="application/json",
            )


    # if a GET (or any other method) we'll create a blank form
    else:
        form = ReportForm()

    return render(request, 'form.html', {'form': form})

@csrf_exempt
def add_report_flutter(request):
    data_admin = User.objects.filter(admin=True).filter(staff=False)
    if len(data_admin) != 0:
        index = random.randint(0, len(data_admin)-1)
    elif len(data_admin) == 0:
        index = -1

    if request.method == 'POST':
        if index == -1:
            dataAdmin = None
        else:
            dataAdmin = data_admin[index]

        data = json.loads(request.body)
    
        report = Report(
            user_submission = User.objects.get(pk=data['user_submission']),
            admin_submission = dataAdmin,
            title = data['title'],
            content = data['content'],
            institution = data['institution'],
            institution_level = data['institution_level'],
            involved_party = data['involved_party'],
            location = data['location'],
            date = data['date'],
            status = "PENDING"
        )
        report.save()
        return JsonResponse({"status": "success"}, status = 200)
    else:
        return JsonResponse({"status": "error"}, status = 401)

submission_form/templates/form.html
{% extends 'base.html' %} {% block meta %}
<title>Submission Form</title>
{% endblock meta %} {% block content %}
<html lang="en" data-theme="garden">
<head>
    <link rel="stylesheet" href="/static/style.css" />
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.33.0/dist/full.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tiny.cloud/1/c7j6uduau6zir133y2k9hlsbh3ek3e0pv1l3re3iddnr8vi4/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
</head>

{% load static %}

<div class="container min-h-screen min-w-full bg-[#134D52] mx-auto">
    <div class="navbar bg-[#142930]/50 fixed backdrop-blur-[2px] shadow-lg">
        <div class="flex-1">
          <a class="btn btn-ghost normal-case text-xl" id="navbarLogo">
            <img src="{% static 'Group 94.png' %}"></img>
          </a>
        </div>
        <div class="flex-none">
            <ul class="menu menu-horizontal menu-center p-0 bg-white rounded-lg">
                <li id="dashboardBtn"><a class="text-base text-[#142930]">Dashboard</a></li>
            </ul>
          <div class="dropdown dropdown-end">
            <button class="flex justify-center py-[12px] px-[20px] gap-[8px]">
                <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12.5 6C12.5 7.38071 11.3807 8.5 10 8.5C8.61929 8.5 7.5 7.38071 7.5 6C7.5 4.61929 8.61929 3.5 10 3.5C11.3807 3.5 12.5 4.61929 12.5 6ZM3.51894 17.5C3.77426 14.1438 6.57839 11.5 10 11.5C13.4216 11.5 16.2257 14.1438 16.4811 17.5H3.51894Z" fill="#FFFFE7" stroke="#FFFFE7"/>
                </svg>
                <p id="username" class="text-base text-[#FFFFE7] hover:text-[#FDEFB8] hover:underline hover:underline-offset-4">Hello, {{nama}}</p>
            </button>
            <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
              <li id="profileBtn"><a class="text-primary">Profile</a></li>
              <li id="logoutBtn"><a class="text-error">Logout</a></li>
            </ul>
          </div>
        </div>
    </div>

    <div class="container flex flex-col gap-4 pt-8 mx-auto">
        <h1 class="text-4xl judul font-bold text-center text-[#FFFFE7] pt-20">Buat Laporan</h1>
        <div class="rounded-lg p-4 flex flex-col gap-4 shadow-lg 2xl:mx20 xl:mx-20 lg:mx-16 md:mx-14 sm:mx-12 my-8 bg-[#FFFFE7]">

            <form method="POST">
            {% csrf_token %}
                <div class="flex flex-col gap-4">

                    <div class="form-control w-full">
                        <label class="label" for="title">
                            <span class="label-text">Judul  Laporan<span class="label-text text-error">*</span></span>
                        </label>
                        <input id="title" type="text" placeholder="Tuliskan Judul Laporan" class="input input-bordered w-full"/>
                    </div>
        
                    <div class="form-control w-full"> 
                        <label class="label" for="content">
                            <span class="label-text">Isi Laporan<span class="label-text text-error">*</span></span>
                        </label>
                        <textarea id="content" class="textarea textarea-bordered" placeholder="Tuliskan Isi Laporan"></textarea>
                    </div>

                    <div class="form-control w-full">
                        <label class="label" for="institution">
                            <span class="label-text">Instansi terkait<span class="label-text text-error">*</span></span>
                        </label>
                        <input id="institution" type="text" placeholder="Tuliskan Instansi Terkait" class="input input-bordered w-full" />
                    </div>

                    <div class="form-control w-full">
                        <label class="label" for="institution_level">
                            <span class="label-text">Tingkat instansi<span class="label-text text-error">*</span></span>
                        </label>
                        <select name="institution_level" id="institution_level" class="select select-bordered w-full">
                            <option>Pilih tingkat instansi</option>
                            <option value="Nasional">Nasional</option>
                            <option value="Provinsi">Provinsi</option>
                            <option value="Kabupaten/Kota">Kabupaten/Kota</option>
                            <option value="Kecamatan">Kecamatan</option>
                            <option value="Desa/Kelurahan">Desa/Kelurahan</option>
                        </select>
                    </div>

                    <div class="form-control w-full">
                        <label class="label" for="involved_party">
                            <span class="label-text">Pihak yang terlibat<span class="label-text text-error">*</span></span>
                        </label>
                        <input id="involved_party" type="text" placeholder="Nama/Jabatan Pihak yang Terlibat" class="input input-bordered w-full" />
                    </div>

                    <div class="form-control w-full">
                        <label class="label" for="location">
                            <span class="label-text">Lokasi<span class="label-text text-error">*</span></span>
                        </label>
                        <input id="location" type="text" placeholder="Lokasi" class="input input-bordered w-full" />
                    </div>

                    <div class="form-control w-full">
                        <label class="label" for="date">
                            <span class="label-text">Tanggal<span class="label-text text-error">*</span></span>
                        </label>
                        <input type="date" id="date" type="text" placeholder="Tanggal" class="input input-bordered w-full" />
                    </div>

                    <div class="form-control">
                        <label class="label cursor-pointer">
                            <input type="checkbox" id="integrity" class="checkbox checkbox-success bg-base-100"/>
                            <span class="label-text px-4">Saya menyatakan bahwa laporan yang saya buat ini benar, tidak ada unsur manipulasi di dalamnya, dan saya akan bertanggung jawab sepenuhnya terhadap laporan ini</span> 
                        </label>
                    </div>
                    
                    <ul class="msg" id="alert">
                    </ul>
    
                    <button class="btn btn-primary" id="submitBtn" type="submit"><a class="text text-[#FFFFE7]">Submit Laporan</a></button>
                </div>
        </form>
        </div>
    </div>
    <br>
</div>

  <script>
    tinymce.init({
        selector: 'textarea',
        height: 200,
        menubar: false,
        plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table paste code help wordcount'
        ],
        toolbar: 'undo redo | formatselect | ' +
        'bold italic strikethrough | alignleft aligncenter ' +
        'alignright alignjustify | emojis | bullist numlist outdent indent | ' +
        'removeformat',
    });
    // amanin lagi
    function addData(e){
        e.preventDefault();
            const title = $("#title").val()
            const content= tinyMCE.activeEditor.getContent()
            const institution = $("#institution").val()
            const institution_level = $("#institution_level").val()
            const involved_party = $("#involved_party").val()
            const location = $("#location").val()
            const date = $("#date").val()

            const data = {
                title,
                content,
                institution,
                institution_level,
                involved_party,
                location,
                date,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            }
            $('#alert').empty();
            if (!$("input#integrity").is(":checked")){
                $('#alert').append(
                    `
                    <div class="alert alert-error shadow-lg">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                        <span class="label-text">Pernyataan integritas belum dicentang!</span>
                        </div>
                    </div>
                    `
                )
            } else {
                $.ajax({
                    type: "POST",
                    url: "{% url 'submission_form:create_report' %}",
                    data: data,
                    dataType: "json",
                    success: function () {
                        // window.location.href = "{% url 'submission_form:get_json' %}";  
                        $('#alert').append(
                            `
                            <div class="alert alert-success shadow-lg">
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                                <span class="label-text">Laporan berhasil dikirimkan</span>
                                </div>
                            </div>
                            `
                        )
                        goToDashboard();
                    },
                    error: function () {
                        $('#alert').append(
                            `
                            <div class="alert alert-error shadow-lg">
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                                <span class="label-text">Semua isian harus dilengkapi!</span>
                                </div>
                            </div>
                            `
                        )
                    }

                });
            }
            
        }
    function gotToHome(){
        window.location.href = "{% url 'main_page:show_main_page' %}";
    }
    function logout(){
        window.location.href = "{% url 'login:logout' %}";
    }
    function goToProfile(){
        window.location.href = "{% url 'login:show_profile' user.id %}";
    }
    function goToDashboard(){
        window.location.href = "{% url 'dashboard_user:show_reports' %}";
    }
    $(document).ready(function(){
        $("#submitBtn").click(addData)
        $("#navbarLogo").click(gotToHome)
        $("#logoutBtn").click(logout)
        $("#profileBtn").click(goToProfile)
        $("#dashboardBtn").click(goToDashboard)
    }); 
  </script>
{% endblock content %}